#!/bin/bash
# Script to output environment variables for easy copying to Vercel

echo "=== FIREBASE CONFIGURATION ==="
echo "VITE_FIREBASE_API_KEY=AIzaSyDZw3QJBDlsn10pBbtQmBU61Nfa9bMUFx4"
echo "VITE_FIREBASE_AUTH_DOMAIN=onsi-de85f.firebaseapp.com"
echo "VITE_FIREBASE_PROJECT_ID=onsi-de85f"
echo "VITE_FIREBASE_STORAGE_BUCKET=onsi-de85f.firebasestorage.app"
echo "VITE_FIREBASE_MESSAGING_SENDER_ID=304484751803"
echo "VITE_FIREBASE_APP_ID=1:304484751803:web:4031fad794705c0bac8c9e"
echo "VITE_FIREBASE_MEASUREMENT_ID=G-5MF3MSH2J5"
echo ""
echo "=== EMAILJS CONFIGURATION ==="
echo "VITE_EMAILJS_PUBLIC_KEY=ryB3eYn0HP-iAfl2E"
echo "VITE_EMAILJS_SERVICE_ID=service_j4hv4we"
echo "VITE_EMAILJS_CUSTOMER_TEMPLATE_ID=template_3m8gczh"
echo "VITE_EMAILJS_ADMIN_TEMPLATE_ID=template_lkl5yxm"
echo "VITE_ADMIN_EMAIL=rayentroudi00@gmail.com"
echo ""
echo "=== APPLICATION CONFIGURATION ==="
echo "VITE_APP_NAME=Onsi Koran Shop"
echo "VITE_PRODUCT_PRICE=39.00"
echo "VITE_SHIPPING_COST=0.00"
echo "VITE_TAX_RATE=0.00"
echo ""
echo "=== COPY THE ABOVE TO VERCEL ENVIRONMENT VARIABLES ==="